### ISSUE TITLE
seg fault when dumping values of a per-atom compute

### ISSUE THREAD

**Issue by chu-k** [Adrian-Diaz/Temporary_CAC#25]
Reproducible with normal CAC energy min with a compute/dump, eg:
```
compute			centro all centro/atom fcc
dump 			1 all cfg 500 *.cfg mass type xs ys zs c_centro

```
![image](https://user-images.githubusercontent.com/3358071/55511039-98e25e80-562d-11e9-8ca0-68539456341e.png)

**Comment by Adrian-Diaz** [comment]
Have you tried seeing if it works without NEBCAC? a typical CAC dynamics run etc. This might be a case of memory corruption. If I had a dime for every time an array error way before caused a random segfault somewhere else I'd probably have a dollar by now; the joys of C++. Something like valgrind or DDT (if your school has access to it somehow) would provide a more definitive cause.

**Comment by Adrian-Diaz** [comment]
Also try changing the compiler settings to -O0 to reduce optimization. This can flag corruption a lot earlier in many cases.

**Comment by Adrian-Diaz** [comment]
If using a dynamics run (which is the code I've made sure so far has as few memory corruption causes as possible) still induces this on the latest master build send me your input and I'll take a crack at it using DDT on my end; that would be a valuable instance indeed (if it occurs on less than 64 tasks due to debugger constraints) since the other posted issue has something to do with a subtle bug left somewhere I suspect.

**Comment by chu-k** [comment]
Joys indeed, valgrind says the array that tracks all pages is not allocated (or freed prior to the reset). My guess is that the per-atom compute doesn't play nice with the CAC data structures?
Just compiled without optimization and compared a normal CAC statics run and a nve_CAC run; same error on both. 
I've tried cna/atom, coord/atom, and pe/atom (this one doesn't crash but valgrind complains alot about unitialized values and doesn't dump the compute).
 [Input file](https://pastebin.com/ZN8X4wFz) and [CAC model file](https://pastebin.com/rqUzMWqn).

![image](https://user-images.githubusercontent.com/3358071/55592261-ecc07680-5705-11e9-88cf-fcf08e46c488.png)

**Comment by Adrian-Diaz** [comment]
Try changing the initialization for page and oneatom to a non-zero value in the constructor for Pair_CAC.cpp and see what happens

**Comment by Adrian-Diaz** [comment]
In my newest version that I havnt uploaded with comms I set pgsize to 10 and one atom to 1

**Comment by chu-k** [comment]
Yep just ran it with those values and no crash. Looks like that solves it. Thanks for the help!
